version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd frontend && npm install
  build:
    commands:
      - echo Build started...
      - npm run build
artifacts:
  files:
    - "*"
    - "**/*"
  base_directory: "frontend/build/"