AWSTemplateFormatVersion: 2010-09-09
Description: React Web app hosted on S3

Parameters:
  Stage:
    Type: String
    Default: dev
  AppName: 
    Type: String
    Default: poppyland-journal

Resources:
  # Bucket that hosts the website
  DeployBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref AppName
      ObjectOwnership: BucketOwnerPreferred
      WebsiteConfiguration:
        IndexDocument: index.html
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
        - AllowedOrigins: ['*']
          AllowedMethods: [GET]

  # Bucket policy that hosts the website
  DeploymentBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref DeployBucket
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - "s3:GetObject"
            Effect: "Allow"
            Resource: 
              Fn::Join: 
                - ""
                - 
                  - "arn:aws:s3:::"
                  - 
                    Ref: DeployBucket
                  - "/*"
            Principal: "*"